package split;

import java.io.File;
import java.io.FileNotFoundException;
import java.io.PrintWriter;
import java.util.Date;
public class Instancer {
	public double[][] distancias;
	public Instancer(String outputdir,String instancename,int graphnum) throws FileNotFoundException{
		writeIni(outputdir,instancename,graphnum);
	}
	
	public static void writeIni(String outputdir,String instancename,int graphnum) throws FileNotFoundException{
		String ruta = "./data/" + outputdir + "-" +instancename + "/";
		String nombreF = instancename+"_"+graphnum+".ini";
		File directorioFacturas = new File(ruta);
		if(!directorioFacturas.exists())
			directorioFacturas.mkdirs();
		File archivoFactura = new File(directorioFacturas, nombreF);
		PrintWriter out = new PrintWriter(archivoFactura);

		out.println("# ===========================================================================================");
		out.println("# CMR - Vehicle Routing Problem - Instance file");
		out.println("# ===========================================================================================");
		out.println("# Instance File : CMRVRP-1-1-1.ini");
		out.println("# Instance      : " + instancename+"_"+graphnum);
		out.println("# Created       : 22/03/2015");
		out.println("# Created by    : John Fontecha");
		out.println("# Created for   : Testing jVRP components"); 
		out.println("# -------------------------------------------------------------------------------------------");
		out.println("DEMAND_FILE          = ./data/" + outputdir + "-" +instancename + "/" +instancename +"_"+graphnum+ "-demandFile"+graphnum+".csv");
		out.println("CAPACITY_FILE        = ./data/" + outputdir + "-" +instancename + "/" +instancename +"_"+graphnum+ "-capacityFile"+graphnum+".csv");
		out.println("DISTANCE_FILE        = ./data/" + outputdir + "-" +instancename + "/" +instancename +"_"+graphnum+ "-distanceFile"+graphnum+".csv");
		out.println("CORRELATION_FILE     = ./data/" + outputdir + "-" +instancename + "/" +instancename +"_"+graphnum+ "-correlationFile"+graphnum+".csv");
		out.println("DEMAND_TYPE          = vrpModel.DeterministicDemand");
		out.println("# ------------------------------------------------------------------------------------------");
		out.close();
	}	

//	public PrintWriter getWriter(String type, String description, String format) throws FileNotFoundException{
//		String ruta = "./data/" + outputDir + "-" +instanceName + "/";
//		String nombreF = instanceName	+ "-" + type + ".csv";
//		File directorioFacturas = new File( ruta );
//		if( !directorioFacturas.exists( ) )
//			directorioFacturas.mkdirs( );
//		File archivoFactura = new File( directorioFacturas, nombreF );
//		PrintWriter out = new PrintWriter( archivoFactura );
//
//		out.println("#---------------------------------------------------------------------------");
//		out.println("# " + description);
//		out.println("#---------------------------------------------------------------------------");
//		out.println("# Automatically generated by John Fontecha on "+(new Date()).toGMTString());
//		out.println("# Instance source file: '" + instanceName + "'");
//		out.println("#---------------------------------------------------------------------------");
//		out.println("# Centro de Optimización y Probabilidad Aplicada (COPA).");
//		out.println("# e-mail: copa@uniandes.edu.co");
//		out.println("# url:    http://copa.uniandes.edu.co");
//		out.println("#---------------------------------------------------------------------------");
//		out.println("# CSV format: " + format);
//		out.println("# Note: product ID is set to 1 for a single-product VRP.");
//		out.println("#---------------------------------------------------------------------------");
//
//		return out;
//	}
}